### ISSUE TITLE
cannot load such file -- protoc-gen-openapiv2/options/annotations_pb

### ISSUE THREAD

**Issue by dzakaammar** [flipt-io/flipt-grpc-ruby#23]
hi, i try to follow the example but getting this error. could someone help me?

Ruby version:
`ruby 2.6.9p207 (2021-11-24 revision 67954) [arm64-darwin21]`

Gemfile:
```
source "https://rubygems.pkg.github.com/flipt-io" do
  gem "flipt-grpc", "1.4.0"
end

gem 'grpc', '1.53.0'
```

Gemfile.lock:
```
GEM
  remote: https://rubygems.pkg.github.com/flipt-io/
  specs:
    flipt-grpc (1.4.0)
      grpc (~> 1.0)
    google-protobuf (3.22.2-arm64-darwin)
    googleapis-common-protos-types (1.5.0)
      google-protobuf (~> 3.14)
    grpc (1.53.0)
      google-protobuf (~> 3.21)
      googleapis-common-protos-types (~> 1.0)

PLATFORMS
  ruby

DEPENDENCIES
  flipt-grpc (= 1.4.0)!
  grpc (= 1.53.0)

BUNDLED WITH
   1.17.2
```

Full error message:
```
bundler: failed to load command: flipt.rb (flipt.rb)
LoadError: cannot load such file -- protoc-gen-openapiv2/options/annotations_pb
  /Users/dzakaammar/.rbenv/versions/2.6.9/lib/ruby/gems/2.6.0/gems/flipt-grpc-1.4.0/lib/flipt_pb.rb:8:in `require'
  /Users/dzakaammar/.rbenv/versions/2.6.9/lib/ruby/gems/2.6.0/gems/flipt-grpc-1.4.0/lib/flipt_pb.rb:8:in `<top (required)>'
  /Users/dzakaammar/.rbenv/versions/2.6.9/lib/ruby/gems/2.6.0/gems/flipt-grpc-1.4.0/lib/flipt_services_pb.rb:5:in `require'
  /Users/dzakaammar/.rbenv/versions/2.6.9/lib/ruby/gems/2.6.0/gems/flipt-grpc-1.4.0/lib/flipt_services_pb.rb:5:in `<top (required)>'
  flipt.rb:4:in `require'
  flipt.rb:4:in `<top (required)>'
```

**Comment by GeorgeMac** [comment]
Hi @dzakaammar 👋 Thanks for bringing this to our attention.

I believe we're running into a similar issue to what is described here: https://github.com/grpc-ecosystem/grpc-gateway/issues/3155

I think some unwanted openapi annotations slipped through the net into our Ruby gem.
Just need to figure out specifically what and where we can move this out into configuration.

**Comment by GeorgeMac** [comment]
I've got a couple PRs up I believe fix the problem.
I ran the example project with this PR and it worked as expected.

**Comment by GeorgeMac** [comment]
Hi @dzakaammar could you try again with gem version `v1.4.1` for me?

**Comment by dzakaammar** [comment]
thank you @GeorgeMac for your help. it's working fine now.

**Comment by GeorgeMac** [comment]
Thanks again for reporting it @dzakaammar 🙌
